#pragma config(Motor,  port1,           RightFront,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightBack,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LeftBack,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
