#pragma config(Motor,  port2,           DriveRight,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           DriveLeft,     tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)
	{
		motor[DriveRight] = vexRT[Ch3];
		motor[DriveLeft] = vexRT[Ch2];
	}

}
